/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CbDropdown {
        "dataSource": Array<object>;
        "getSelectedData": () => Promise<string>;
    }
    interface CbJsonformatter {
        "cols": number;
        "dataSource": Array<object> | object | string;
        "rows": number;
    }
    interface CbTreeview {
        "dataSource": Array<object> | string;
        "getCheckedData": () => Promise<any[]>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCbDropdownElement extends Components.CbDropdown, HTMLStencilElement {
    }
    var HTMLCbDropdownElement: {
        prototype: HTMLCbDropdownElement;
        new (): HTMLCbDropdownElement;
    };
    interface HTMLCbJsonformatterElement extends Components.CbJsonformatter, HTMLStencilElement {
    }
    var HTMLCbJsonformatterElement: {
        prototype: HTMLCbJsonformatterElement;
        new (): HTMLCbJsonformatterElement;
    };
    interface HTMLCbTreeviewElement extends Components.CbTreeview, HTMLStencilElement {
    }
    var HTMLCbTreeviewElement: {
        prototype: HTMLCbTreeviewElement;
        new (): HTMLCbTreeviewElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cb-dropdown": HTMLCbDropdownElement;
        "cb-jsonformatter": HTMLCbJsonformatterElement;
        "cb-treeview": HTMLCbTreeviewElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CbDropdown {
        "dataSource"?: Array<object>;
    }
    interface CbJsonformatter {
        "cols"?: number;
        "dataSource"?: Array<object> | object | string;
        "rows"?: number;
    }
    interface CbTreeview {
        "dataSource"?: Array<object> | string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "cb-dropdown": CbDropdown;
        "cb-jsonformatter": CbJsonformatter;
        "cb-treeview": CbTreeview;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cb-dropdown": LocalJSX.CbDropdown & JSXBase.HTMLAttributes<HTMLCbDropdownElement>;
            "cb-jsonformatter": LocalJSX.CbJsonformatter & JSXBase.HTMLAttributes<HTMLCbJsonformatterElement>;
            "cb-treeview": LocalJSX.CbTreeview & JSXBase.HTMLAttributes<HTMLCbTreeviewElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
